permalink: /:year/:month/:day/:slug   # 博文的固定链接
paginate: 5                                # 分页时每页博文数量

title: 磕傁博文                           # 自定义常量
url: https://blog.coso.ink
resource_url: //res.coso.ink

timezone:    Asia/Shanghai
future:      true
rouge:    true


markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart

valine_comment:
  enable: true
# app_id
  leancloud_appid: UbTEcXzPfMVEfpJ8kXQAEUyC-gzGzoHsz
# app_key
  leancloud_appkey: smUurhep6QpENvcr9CN72cJi
# placeholde
  placeholder: "请尽情吐槽~"

author:
    name: 陈俊州
    email: datochan@qq.com
    link: https://blog.coso.ink

logo_list:
    code: //res.coso.ink/public/images/category/code.jpg
    life: //res.coso.ink/public/images/category/life.png
    web: //res.coso.ink/public/images/category/web.png
    data: //res.coso.ink/public/images/category/data.png
    invest: //res.coso.ink/public/images/category/invest.png

subscribe_rss: /pages/atom.xml              #订阅地址
