permalink: /:year/:month/:day/:title.html   # 博文的固定链接
paginate: 10                                # 分页时每页博文数量

title: 陈大头的博客                           # 自定义常量
url: http://datochan.me
resource_url: https://github.com/datochan/datochan.github.io/tree/master

timezone:    Asia/Shanghai
future:      true
pygments:    true

markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart


author:
    name: 陈俊州
    email: datochan@qq.com
    link: http://datochan.me

logo_list:
    code: https://github.com/datochan/datochan.github.io/tree/master/public/images/category/code.jpg
    edx: https://github.com/datochan/datochan.github.io/tree/master/public/images/category/edx.jpg
    life: https://github.com/datochan/datochan.github.io/tree/master/public/images/category/life.png
    web: https://github.com/datochan/datochan.github.io/tree/master/public/images/category/web.png

subscribe_rss: /pages/atom.xml              #订阅地址
