permalink: /:year/:month/:day/:title.html   # 博文的固定链接
paginate: 15                                # 分页时每页博文数量

title: 陈大头的博客                           # 自定义常量
url: http://datochan.me
resource_url: http://7xnsgl.com1.z0.glb.clouddn.com

timezone:    Asia/Shanghai
future:      true
pygments:    true

markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart


author:
    name: 陈俊州
    email: datochan@qq.com
    link: http://datochan.me

logo_list:
    edx: http://7xnsgl.com1.z0.glb.clouddn.com/public/images/category/edx.jpg
    web前端: http://7xnsgl.com1.z0.glb.clouddn.com/public/images/category/web.png

subscribe_rss: /pages/atom.xml              #订阅地址
